export const TB_HEADER_DATA = {
  car: [
    { title: "Date d. transaction", sortable: false },
    { title: "Nom", sortable: false },
    { title: "Coleur", sortable: false },
    { title: "MT (N.CH)", sortable: false },
    { title: "Année", sortable: false },
    { title: "Prix", sortable: false },
  ],
  paper: [
    { title: "Date d. transaction", sortable: false },
    { title: "Propriétaire", sortable: false },
    { title: "Voiture", sortable: false },
    { title: "N.CH", sortable: false },
    { title: "--", sortable: false },
    { title: "Prix", sortable: false },
  ],
  procuration: [
    { title: "Date d. transaction", sortable: false },
    { title: "Propriétaire", sortable: false },
    { title: "Voiture", sortable: false },
    { title: "N.CH", sortable: false },
    { title: "", sortable: false },
    { title: "Prix", sortable: false },
  ],
  Fiat: [
    { title: "Date d. transaction", sortable: false },
    { title: "Destinataire", sortable: false },
    { title: "Méthode", sortable: false },
    { title: "--", sortable: false },
    { title: "--", sortable: false },
    { title: "Montante", sortable: false },
  ],
  licence: [
    { title: "Date d. transaction", sortable: false },
    { title: "Moudjahid", sortable: false },
    { title: "Wilaya", sortable: false },
    { title: "N.Série", sortable: false },
    { title: "--", sortable: false },
    { title: "Prix", sortable: false },
  ],
};
