export const TB_HEADER_DATA = [
  { title: "Indice", sortable: false },
  { title: "Statut", sortable: false },
  { title: "Nom", sortable: true, field: "name" },
  { title: "Num. série", sortable: true, field: "serial_number" },
  { title: "Matricule", sortable: true, field: "registration_number" },
  { title: "Couleur", sortable: true, field: "color" },
  { title: "Année", sortable: true, field: "production_year" },
  { title: "Propriétaire", sortable: true, field: "owner_name" },
  { title: "Date d'achat", sortable: true, field: "purchased_at" },
  { title: "Vendeur", sortable: true, field: "seller" },
  { title: "Coût total", sortable: true, field: "total_cost" },
  { title: "Vendu le", sortable: true, field: "sold_at" },
  { title: "Acheteur", sortable: true, field: "buyer" },
  { title: "Pr. vente", sortable: true, field: "sold_price" },
  { title: "Type", sortable: true, field: "type" },
];
